# Copyright (c) 2020 Huawei Device Co., Ltd. All rights reserved.

include $(LITEOSTOPDIR)/../../drivers/hdf/lite/lite.mk

MODULE_NAME := hdf_config

LOCAL_PLATFORM_HCS_SRC := hdf.hcs

include $(HDF_DRIVER)